
const fs = require('fs');
const path = require('path');

// Generate version: vYYYYMMDD-HHMMSS
const now = new Date();
const version = `v${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}${String(now.getSeconds()).padStart(2, '0')}`;

console.log(`[BUMP] New version: ${version}`);

// Paths
const SW_PATH = path.join(__dirname, '../public/sw.js');
const LIB_VERSION_PATH = path.join(__dirname, '../lib/version.ts');

// 1. Update Service Worker
try {
    let swContent = fs.readFileSync(SW_PATH, 'utf8');

    // Regex to find "const CACHE_VERSION = '...';"
    const versionRegex = /const CACHE_VERSION = ['"].*['"];/;

    if (versionRegex.test(swContent)) {
        swContent = swContent.replace(versionRegex, `const CACHE_VERSION = '${version}';`);
        fs.writeFileSync(SW_PATH, swContent);
        console.log(`[BUMP] Updated public/sw.js`);
    } else {
        console.error(`[BUMP] ERROR: Could not find CACHE_VERSION constant in sw.js`);
        process.exit(1);
    }
} catch (e) {
    console.error(`[BUMP] Failed to update sw.js:`, e);
    process.exit(1);
}

// 2. Update lib/version.ts
const versionFileContent = `// Auto-generated by scripts/bump-version.js
export const APP_VERSION = '${version}';
export const BUILD_DATE = '${now.toISOString()}';
`;

try {
    fs.writeFileSync(LIB_VERSION_PATH, versionFileContent);
    console.log(`[BUMP] Updated lib/version.ts`);
} catch (e) {
    console.error(`[BUMP] Failed to update lib/version.ts:`, e);
    process.exit(1);
}
