"use client"

import React from "react"
import { Sparkles, Terminal, Copy } from "lucide-react"

export function CreditsApp() {

    const wallpapers = [
        {
            name: "Ubuntu",
            prompt: "Ubuntu themed abstract wallpaper, desktop resolution 1920x1080. Orange and purple gradient, geometric shapes, canonical style, slick, modern, linux desktop background.",
            preview: "/wallpapers/ubuntu-desktop.png"
        },
        {
            name: "Ocean",
            prompt: "Deep ocean blue aesthetic wallpaper, desktop resolution 1920x1080. Dark blue tones, underwater vibes, calm, minimal, slick, digital art.",
            preview: "/wallpapers/ocean-desktop.png"
        },
        {
            name: "Dracula",
            prompt: "Dracula theme wallpaper, desktop resolution 1920x1080. Dark grey background with pink, purple, and green neon accents. Vampire aesthetic but minimal and tech-oriented. Coding theme.",
            preview: "/wallpapers/dracula-desktop.png"
        }
    ]

    return (
        <div className="h-full bg-zinc-900 text-zinc-300 font-sans flex flex-col items-center p-8 overflow-y-auto">

            <div className="max-w-2xl w-full space-y-8">
                {/* Header / Shoutout */}
                <div className="text-center space-y-4">
                    <div className="w-20 h-20 bg-gradient-to-tr from-blue-500 to-purple-500 rounded-2xl mx-auto flex items-center justify-center shadow-2xl shadow-purple-500/20">
                        <Sparkles className="text-white w-10 h-10" />
                    </div>
                    <h1 className="text-3xl font-bold text-white tracking-tight">Wallpaper Credits</h1>
                    <p className="text-lg text-zinc-400">
                        Generated by <span className="text-blue-400 font-bold">Gemini Pro</span> (Google DeepMind).
                    </p>
                    <div className="bg-zinc-800/50 p-4 rounded-xl border border-zinc-700/50 text-sm">
                        <p>
                            All wallpapers in this portfolio OS were generated using the Antigravity agent powered by Gemini.
                            Below are the exact prompts used to create them.
                        </p>
                    </div>
                </div>

                {/* Wallpapers List */}
                <div className="space-y-8">
                    {wallpapers.map((wp) => (
                        <div key={wp.name} className="bg-zinc-800 rounded-xl overflow-hidden border border-zinc-700 hover:border-zinc-600 transition-colors">
                            {/* Preview */}
                            <div className="h-48 overflow-hidden relative group">
                                <div className="absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-105" style={{ backgroundImage: `url(${wp.preview})` }} />
                                <div className="absolute inset-0 bg-gradient-to-t from-zinc-900/90 to-transparent flex items-end p-6">
                                    <h3 className="text-xl font-bold text-white">{wp.name} Theme</h3>
                                </div>
                            </div>

                            {/* Prompt Code Block */}
                            <div className="p-4 bg-black/40">
                                <div className="flex items-center justify-between mb-2">
                                    <span className="text-xs font-mono text-zinc-500 uppercase tracking-widest flex items-center gap-2">
                                        <Terminal size={12} /> Prompt
                                    </span>
                                </div>
                                <div className="font-mono text-xs text-green-400 bg-black p-3 rounded-lg border border-zinc-800 leading-relaxed relative">
                                    {wp.prompt}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="text-center text-xs text-zinc-600 pt-8">
                    Portfolio OS v2.0 • 2025
                </div>
            </div>
        </div>
    )
}
